### ISSUE TITLE
Creating underground pipes sometimes skip pumpjacks

### ISSUE THREAD

**Issue by Pietersielie** [Xcone/factorio_pump#10]
Still a wonderful mod, can't play without it. ;D Found an occasional error where a pumpjack would be skipped after an underground section is created. I've not been able to figure out what caused it, just how it looks at the end.
![PUMP_Error](https://user-images.githubusercontent.com/41905461/136082809-7a8c2249-8d9b-4efc-b461-13f5732d8c0f.png)
As per the request on the mod page, I attach [pump_planner_input.zip](https://github.com/Xcone/factorio_pump/files/7288416/pump_planner_input.zip) (for the oil field detailed above). I also provide a [minimal save](https://github.com/Xcone/factorio_pump/files/7288572/P.U.M.P.Error.zip) (Editor Extensions only as "cheat" along with P.U.M.P.) detailing the two oil fields where I found this issue.
![PUMP_Error2](https://user-images.githubusercontent.com/41905461/136086048-f0a9182e-18e0-4f71-a92b-ac9019baec57.png)

**Comment by Xcone** [comment]
Fixed the issue. It seems to be slightly luck-bound and order-of-execution sensitive. 

You were correct that it is the underground section of another pump that caused the issue of the pump not connection.
Or more precisely, P.U.M.P. plans out all pipes above ground first. And after the layout is complete it'll bury stretches of straight pipes. Unfortunately, the information it shouldn't bury the output of the pumps sometimes got overwritten. 

In both your screenshots the pump missing the pipe was planned first, the output of the pipe was marked as essential to keep above ground. But that essential flag got removed/overwritten when the pump to the right of it got planned, and plotted its pipe right on top of it and thus marking it as regular pipe instead. Later on the pipe-burying routine no longer has the info to keep that particular pipe above ground; therefor, unconnected pump.

Had the pump on the right be planned first, and the pump the left planned on top of it, the issue wouldn't be there, as no essential markings would've been deleted.

Issue is fixed by checking if a pipe has already been planned for a tile before planning a regular pipe on top of it.
