### ISSUE TITLE
Crash when trying to plan 4 nearby oil spots.

### ISSUE THREAD

**Issue by Nikey646** [Xcone/factorio_pump#2]
World generaation was via RSO.

> 15609.753 Error MainLoop.cpp:1207: Exception at tick 5878560: The mod P.U.M.P. (0.1.7) caused a non-recoverable error.
> Please report this error to the mod author.
> 
> Error while running event pump::on_player_selected_area (ID 49)
> __pump__/planner.lua:485: attempt to index field '?' (a nil value)
> stack traceback:
> 	[\_\_pump__/planner.lua:485](https://github.com/Xcone/factorio_pump/blob/master/mod/planner.lua#L338): in function 'area_contains_obstruction'
> 	[\_\_pump__/planner.lua:451](https://github.com/Xcone/factorio_pump/blob/master/mod/planner.lua#L338): in function 'find_split'
> 	[\_\_pump__/planner.lua:342](https://github.com/Xcone/factorio_pump/blob/master/mod/planner.lua#L338): in function 'segmentate'
> 	[\_\_pump__/planner.lua:386](https://github.com/Xcone/factorio_pump/blob/master/mod/planner.lua#L338): in function 'split_segment'
> 	[\_\_pump__/planner.lua:338](https://github.com/Xcone/factorio_pump/blob/master/mod/planner.lua#L338): in function 'segmentate'
> 	[\_\_pump__/planner.lua:31](https://github.com/Xcone/factorio_pump/blob/master/mod/planner.lua#L31): in function 'add_construction_plan'
> 	[\_\_pump__/control.lua:33](https://github.com/Xcone/factorio_pump/blob/master/mod/control.lua#L33): in function 'process_selected_area_with_this_mod'
> 	[\_\_pump__/control.lua:8](https://github.com/Xcone/factorio_pump/blob/master/mod/control.lua#L8): in function <\_\_pump__/control.lua:6>

[pump_planner_input.zip](https://github.com/Xcone/factorio_pump/files/5146406/pump_planner_input.zip)

![image](https://user-images.githubusercontent.com/7837522/91652652-acbd1900-eadc-11ea-9438-e955f6f6a6e7.png)

Tested various sets to see if it was the area in general or just a certain set... Doing any combination of the bottom 3 (Hidden under grass) doesn't produce an error, doing the top one and the two left most ones is fine as well. It only seems to occur when attempting all 4, seemingly due to the limited amount of space available.

Two  examples of generated setups.
![image](https://user-images.githubusercontent.com/7837522/91652689-e9891000-eadc-11ea-9311-0394df68a766.png)
![image](https://user-images.githubusercontent.com/7837522/91652693-f3ab0e80-eadc-11ea-9e72-88d7bcddc87e.png)

Neither of these two plans actually create a setup of pipes that would allow the 4th one to be placed, which is what leads me to believe that it's the issue.

**Comment by Xcone** [comment]
Hi, thank you for reporting the issue.

I've ran the provided input file in a test tool I made to develop the mod, and unfortunately was not able to reproduce it with it. Did you by any chance first try other layouts that didn't crash before grabbing the file and attaching it? Each plan-action overwrites the file. So if the last attempt does not produce the error the file will produce a healthy result for me. Looking at the input file you've attached, I suspect the belongs to the layout of the last picture you shared.

If you're sure you did grab the file right after the crash, then it appears the bug is locating in the selection-part of the tool, and not the layouting. Which means the file will unfortunately not give me the info I need to resolve the issue. In this case, would you mind sharing the save file of this world and give the coordinates of the fields where this issue occurs. Hopefully I'll be able to reproduce it in game.

Thanks again for the report. Looking forward to fixing it. :-)

**Comment by Nikey646** [comment]
Sadly, the mod doesn't actually produce the pump planner input when this crash occurs, the script-output folder is actually empty!

I confirmed this via deleting the existing files inside of script-output and seeing that nothing is created when the mod causes an error.

So in that case, here is the save file. I've already loaded it without any other mods and confirmed that it still crashes when trying to do all 4 spots, and have placed the power armor w/ some shields and legs (no energy source, was modded :D) into the crashed ship.... The defenses may or may not have relied on modded walls, so biters may or may not be eating the base.

There is a pumpjack map icon at the location of the oil well, and the coordinates are x: -452, and y: -487.

For future reference, informing players that they can get the coordindates via using the following command: `/c game.player.print('x='..game.player.character.position.x..' y='..game.player.character.position.y)` (I had to look it up :s)

[PumpError.zip](https://github.com/Xcone/factorio_pump/files/5146492/PumpError.zip)

**Comment by Nikey646** [comment]
As a side note, the oil wells to the east of the one causing a crash has a funny placement. You can see in the top right of below image that it for some reason it wants to connect the side of an underground pipe to the pump jack.

![image](https://user-images.githubusercontent.com/7837522/91656083-13503000-eaf9-11ea-9a27-a8a875ec0fe6.png)

**Comment by Xcone** [comment]
Thanks for the save. I can reproduce both issues with it. I'll start working on a fix a.s.a.p.

**Comment by Xcone** [comment]
I found the cause of both your issues and was able to fix them. A new version has been uploaded to the mod portal.

If your interested, as well as for my own future reference, a little bit of background:
The problem was caused by the order in which rows/columns are being checked for obstructions by P.U.M.P.
In the image below the blocks represent the tiles of your selection. Green is buildable, 'P' is the pump, and orange is the size of the pump. Red is obstructed (either trees/rocks/water). 
P.U.M.P. works by trying the find 'somewhat even splits. So it starts in the middle of the selection, and then works outwards. The digits represent the order it checks columns for obstructions.

Normally there's spacing between pumps, so the pipe would end up in between pumps. In this case there's no room for that. So the next best thing is no obstructions on the outside edge, so the pipe would be layed 'around', which would result in column 6 being selected for the pipe. But this column had an obstruction (the water). And due to an unfortunate order, the P.U.M.P. ended up evaluation column 8, .. which is actually not part of the selection, causing the crash.
![image](https://user-images.githubusercontent.com/10597379/91671185-a8b4e980-eb24-11ea-8241-ea5c9920c644.png)

**Comment by Nikey646** [comment]
That is actually really amusing.

Is there any reason you haven't considered marking obstructions for deconstruction, or in the case of water marking it will a ghost of landfill?

Presumably, since you're already placing ghosts of the pumps and pipes, it would all work, and the robots could just remove / fill the missing chunks. I feel like, at least personally, having the mod just do those kind of chores would be easier.

**Comment by Xcone** [comment]
It is considered. I don't want to auto fill water. Looking at my personal play style, I barely ever have landfill on me. So I don't want P.U.M.P. to rely on it, because I feel it can just as often be annoying as it can be helpful. This means I had to work with obstructions anyway. And therefor I have put off auto removing trees as a 'maybe later' feature.
