### ISSUE TITLE
Off by one error for some pipes

### ISSUE THREAD

**Issue by Pietersielie** [Xcone/factorio_pump#3]
I have a field of 22 pumpjacks, but there were two spots where the pipes left a gap of one tile and didn't connect. I've circled the areas in the screenshot below.
![Oil_Field_off-by-one](https://user-images.githubusercontent.com/41905461/93667368-b1467300-fa85-11ea-821a-ea7f92bb3cef.png)

I link a zip containing the output log and the save file, too big to upload here. Word of warning, it is a megabase rated for around 2k SPM, so it is huge. There are about 20 utility mods I use, but the only ones adding or removing items are the power component of Factorio Extended+, and Noxy's Waterfill, neither of which touch oil or pipes to my knowledge.

https://drive.google.com/file/d/1mM8BVOKivNNINKvlOtA_c1tR_lwictzb/view?usp=sharing

The oil field in question is at the far top right corner of the base, next to the Spidertron.

**Comment by Pietersielie** [comment]
The mods I use in this save are:
- Afraid of the dark
- Alien Biomes
- Auto deconstruct
- Automatic Station Painter
- Automatic Train Painter
- Calculator UI
- Car/Tank/Spidertron Locator Button
- Even Distribution
- FactorioExtended Plus-Core
- FactorioExtended Plus-Power
- Long Reach
- Max Rate Calculator
- Noxys Waterfill
- P.U.M.P.
- Pavement Drive Assist
- Renamer
- Santa's Nixie Tube Display
- Squeak Through
- Text Plates
- Todo List
- Wood stack 1k

**Comment by Xcone** [comment]
Awesome feature by the devs for the mod-synchronization feature when loading a save file! Makes loading someone else's save incredibly easy. I'm able to reproduce the issue, so I'll get working on it when I'm able. 

You weren't kidding with the size of the base, by the way. If you don't mind, I might take try and take some pointers out of it for when I play myself. I've never been able to pass 1KSPM, after which my train system clogged. But first, .. this issue 👍

**Comment by Pietersielie** [comment]
By all means, do steal as much as you want or can. :) It's my first megabase, but much of the rail blueprints and basic designs (unmoduled stuff essentially) were borrowed from Nilaus over on Youtube, though he used LTN for the trains and I use HTN/VTN, not sure what the name is. And still in the process of ensuring that the raw materials can keep up with 2k SPM, though it can probably get close.

**Comment by Xcone** [comment]
I've uploaded P.U.M.P. 0.1.10 to the mod portal to address this issue. 

At appears your initial suggestion about the pipes being too close was right. 

For a bit of background, as well as for my own future reference:
![image](https://user-images.githubusercontent.com/10597379/93669640-e5299480-fa95-11ea-9889-7b94c3c0a7da.png)
P.U.M.P. splits the fields in half iteratively and places pipes on them. This results in these long lines of pipes all across the field. Each iteration it attempts to connect all the pumps to one of the slits in a straight line, and if it fails it attemps another split. This repeats until all pipes are connected. The result is something like the graphic above, long stretched of pipes all over.

Next, it will replace those long stretches of pipes with tunnels (the green lines), and remove dead-ends (the blue lines).
However, the problem arose in the order in which this happens. The bug you reported here shows the order ended up wrong. And instead it would remove a dead-end in one direction (the red lines), instead of placing a tunnel in the other direction (the yellow lines). This dead-end removal would then prevent the tunnel to be generated later on, because a pipe segment is missing.

I've changed to order a little bit. So now dead-ends won't be removed until all the tunnels are placed. It should fix the issue for you. Thanks again for reporting it.
